# ワークフローの名前（GitHubの画面に表示されます）
name: First Automation

# どのタイミングで実行するか（今回は「push」された時）
on: [push]  ##いつ

# 実行したい処理の塊
jobs:
  greet-job:
    # 実行するマシンのOS（Ubuntuが一般的です）
    runs-on: ubuntu-latest  ##どこで

    # 具体的な手順
    steps:  ##なにを
      - name: Say Hello
        run: error-command "Hello, World! 福岡からエンジニアを目指します！"